import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import localFont from 'next/font/local'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import { Inter } from 'next/font/google'
import MobileMenu from "@/components/mobile-header";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'

})

const circularStd = localFont({
  src: [{
    path: './fonts/CircularStd-Bold.woff2',
    weight: 'bold',
    style: 'normal'
  }],
  variable: '--font-circular-std'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.variable} ${circularStd.variable} font-sans relative`}
      >

        <div className="w-3/4 h-1/2 absolute rounded-full -z-10 left-0 top-0 -translate-x-1/2 -translate-y-1/2
        bg-[radial-gradient(circle_at_center,#FF5722,transparent)] opacity-40 blur-3xl
        overflow-x-hidden
        "></div>
        <Header></Header>

        {children}
      </body>
    </html>
  );
}
